# This is just a sample file. For a fully documented version of this file, see
# https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample
api_key: fakekey
galaxy_instance: http://localhost:8080
install_repository_dependencies: False
install_resolver_dependencies: True
install_tool_dependencies: True
tools:

########### SAMTOOLS
- name: bam_to_sam
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: sam_to_bam
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_bedcov
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_calmd
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_flagstat
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_idxstats
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_mpileup
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_reheader
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_rmdup
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_slice_bam
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_sort
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_split
  owner: devteam
  tool_panel_section_id: 'samtools'

- name: samtools_stats
  owner: devteam
  tool_panel_section_id: 'samtools'
  
- name: package_samtools_1_2
  owner: iuc
  tool_panel_section_id: 'samtools'

#####################
#####################
#####################

########### BEDTOOLS
- name: bedtools
  owner: iuc
  tool_panel_section_id: 'bedtools'
  
- name: package_bedtools_2_24
  owner: iuc
  tool_panel_section_id: 'bedtools'

#####################
#####################
#####################

########### BAMTOOLS
- name: bamtools
  owner: devteam
  tool_panel_section_id: 'bamtools'
  
- name: package_bamtools_2_3_0_2d7685d2ae
  owner: devteam
  tool_panel_section_id: 'bamtools'

#####################
#####################
#####################

############# VCFTOOLS
- name: all_vcftools
  owner: devteam
  tool_panel_section_id: 'vcftools'
  
- name: package_vcftools_0_1_12b
  owner: iuc
  tool_panel_section_id: 'vcftools'

#####################
#####################
#####################

############## PICARD
- name: picard
  owner: devteam
  tool_panel_section_id: 'picard'
  
- name: package_picard_1_136
  owner: devteam
  tool_panel_section_id: 'picard'
  
#####################
#####################
#####################

############## EMBOSS
- name: emboss_5
  owner: devteam
  tool_panel_section_id: 'emboss'
  
- name: package_emboss_5_0_0
  owner: devteam
  tool_panel_section_id: 'emboss'

#####################
#####################
#####################

############## Bctools
- name: suite_bctools
  owner: iuc
  tool_panel_section_id: 'bctools'

#####################
#####################
#####################

############## Deeptools
- name: suite_deeptools
  owner: bgruening
  tool_panel_section_id: 'deeptools'

#####################
#####################
#####################

################ GATK
- name: gatk2
  owner: iuc
  tool_panel_section_id: 'gatk'

#####################
#####################
#####################
